In [1]:
pip install bluemist

In [2]:
import pandas as pd

from bluemist.environment import initialize
from bluemist.preprocessing import preprocess_data
from bluemist.regression import train_test_evaluate, deploy_model

In [3]:
initialize()
data = pd.read_csv('https://www4.stat.ncsu.edu/~boos/var.select/diabetes.tab.txt', sep='\t')
data.head()

██████╗ ██╗     ██╗   ██╗███████╗███╗   ███╗██╗███████╗████████╗     █████╗ ██╗
██╔══██╗██║     ██║   ██║██╔════╝████╗ ████║██║██╔════╝╚══██╔══╝    ██╔══██╗██║
██████╔╝██║     ██║   ██║█████╗  ██╔████╔██║██║███████╗   ██║       ███████║██║
██╔══██╗██║     ██║   ██║██╔══╝  ██║╚██╔╝██║██║╚════██║   ██║       ██╔══██║██║
██████╔╝███████╗╚██████╔╝███████╗██║ ╚═╝ ██║██║███████║   ██║       ██║  ██║██║
                                (version 0.1.1)

Bluemist path :: /home/shashank-agrawal/PycharmProjects/bluemist-ai/bluemist
System platform :: posix, Linux, 5.19.0-31-generic, linux-x86_64, ('64bit', 'ELF')

   AGE  SEX   BMI     BP   S1     S2    S3   S4      S5  S6    Y
0   59    2  32.1  101.0  157   93.2  38.0  4.0  4.8598  87  151
1   48    1  21.6   87.0  183  103.2  70.0  3.0  3.8918  69   75
2   72    2  30.5   93.0  156   93.6  41.0  4.0  4.6728  85  141
3   24    1  25.3   84.0  198  131.4  40.0  5.0  4.8903  89  206
4   50    1  23.0  101.0  192  125.4  52.0  4.0  4.2905  80  135

In [4]:
# Categorical encoding using OneHotEncoder
X_train, X_test, y_train, y_test = preprocess_data(data, 
                                                   target_variable='Y', 
                                                   test_size=0.25, 
                                                   data_scaling_strategy='StandardScaler',
                                                   categorical_features=['SEX'], 
                                                   categorical_encoder='OneHotEncoder',
                                                   drop_categories_one_hot_encoder='first')
X_train.head()

,AGE,BMI,BP,S1,S2,S3,S4,S5,S6,SEX_2
0,-2.256402,-0.237583,-0.834117,0.975180,1.289605,-0.302383,0.687862,0.125787,-0.668411,0.0
1,1.230453,1.618094,0.520919,-0.006013,0.320029,-1.158176,0.687862,0.605781,0.916937,1.0
2,-1.801595,-0.644927,-0.477529,-1.323615,-1.127958,0.397811,-0.818322,-2.042113,-0.756486,1.0
3,0.320838,1.527573,1.590684,-0.202252,0.090392,-0.146785,-0.065230,-0.516943,1.269236,1.0
4,0.624043,1.188120,1.590684,0.975180,-0.273199,-0.769179,1.440954,2.494051,1.885760,1.0

In [5]:
# Train and compare models
train_test_evaluate(X_train, X_test, y_train, y_test, target_scaling_strategy='MinMaxScaler')

Training TweedieRegressor: 100%|██████████| 46/46 [00:20<00:00,  2.25it/s]

In [ ]:
deploy_model(estimator_name='LinearSVR', host='localhost', port=8000)

INFO:     Started server process [167513]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://localhost:8000 (Press CTRL+C to quit)

INFO:     127.0.0.1:40194 - "GET / HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:40194 - "GET /docs HTTP/1.1" 200 OK
INFO:     127.0.0.1:40194 - "GET /openapi.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:40210 - "POST /predict HTTP/1.1" 200 OK